### ISSUE TITLE
Project file missing

### ISSUE THREAD

**Issue by socketwiz** [ruaridht/Spotify-Menubar#1]
When I try to open the project I am presented with the following error:

Menubar.xcodeproj cannot be opened because it is missing its project.pbxproj file.

I'm using Xcode v4.5.1

**Comment by ruaridht** [comment]
Hi, at the moment I do not have access to the files, though will be able to add any missing files on the 24th October.

**Comment by christowiz** [comment]
Hey, @ruaridht. I was wondering after all these years if that missing file (`project.pbxproj`) was ever found.  Short of creating my own macOS application I'd love to keep this alive.  I've been using this for years and haven't found anything that works as well or as easy.  Thanks.

**Comment by ruaridht** [comment]
Hi @christowiz , I've added the missing file. Just shout if anything else is missing.

**Comment by christowiz** [comment]
That's awesome, @ruaridht!  Thanks so much.
